name: darkness_fix
description: RPG Game.
publish_to: 'none'

version: 1.3.6+12

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Game & UI packages
  bonfire: ^3.13.1
  flame_audio: ^2.10.2
  flame_splash_screen: ^0.3.1
  url_launcher: ^6.3.1
  win32: ^5.10.0
  google_mobile_ads: ^6.0.0

  # Optional
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1  # ✅ Required for logo generation

flutter_icons:  # ✅ Configuration for logo generation
  android: true
  ios: true
  image_path: "assets/icon/1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/icon/1.png
    - assets/new/
    - assets/images/
    - assets/images/emote/
    - assets/images/npc/
    - assets/images/enemy/
    - assets/images/enemy/goblin/
    - assets/images/enemy/imp/
    - assets/images/enemy/mini_boss/
    - assets/images/enemy/boss/
    - assets/images/player/
    - assets/images/items/
    - assets/images/tiled/
    - assets/audio/
    - resources/lang/en.json
    - resources/lang/pt.json

  fonts:
    - family: Normal
      fonts:
        - asset: fonts/font_pixel.ttf
